------------------------------------------------------------------------
-- 1) DROP EXISTING OBJECTS
------------------------------------------------------------------------

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ORDERS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SUPPLIERS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EQUIPMENT CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CLIENTS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE APP_HISTORY CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE CLIENTS_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE EMPLOYEES_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE EQUIPMENT_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE ORDERS_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE REQ_HIST_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SDR_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLIENTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EMPLOYE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EMPLOYEES';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EMPLOYES_ID';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EQUIPMENT';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ORDERS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SUPPLIERS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SUPPLIER_NOTIF_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SUPPLIERS_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

------------------------------------------------------------------------
-- 2) CREATE TABLES
------------------------------------------------------------------------

CREATE TABLE APP_HISTORY
(
    LOG_ID NUMBER,
    LOG_DATE TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    EMPLOYEE_NAME VARCHAR2(200 BYTE),
    ACTION_DETAILS VARCHAR2(1000 BYTE),
    MODULE_NAME VARCHAR2(100 BYTE)
);

CREATE TABLE CLIENTS
(
    CLIENT_ID NUMBER,
    FIRST_NAME VARCHAR2(100 BYTE),
    LAST_NAME VARCHAR2(100 BYTE),
    EMAIL VARCHAR2(150 BYTE),
    PHONE_NUMBER VARCHAR2(20 BYTE),
    ADDRESS VARCHAR2(255 BYTE),
    GENDER VARCHAR2(10 BYTE),
    BIRTH_DATE DATE,
    AGE NUMBER,
    ACCOUNT_BALANCE NUMBER(15,2) DEFAULT 0,
    REGISTRATION_DATE DATE DEFAULT TRUNC(SYSDATE),
    STATUS VARCHAR2(20 BYTE) DEFAULT 'Active',
    ASSIGNED_EMPLOYEE_ID NUMBER
);

CREATE TABLE EMPLOYEES
(
    EMPLOYEE_ID NUMBER,
    FIRST_NAME VARCHAR2(100 BYTE),
    LAST_NAME VARCHAR2(100 BYTE),
    JOB_TITLE VARCHAR2(100 BYTE),
    EMAIL VARCHAR2(150 BYTE),
    PHONE_NUMBER VARCHAR2(20 BYTE),
    SALARY NUMBER(12,2),
    PASSWORD VARCHAR2(255 BYTE),
    DEPARTMENT VARCHAR2(100 BYTE),
    BIRTH_DATE DATE,
    AGE NUMBER,
    HIRE_DATE DATE DEFAULT TRUNC(SYSDATE),
    EMPLOYEE_STATUS VARCHAR2(20 BYTE) DEFAULT 'Active',
    ADDRESS VARCHAR2(200 BYTE)
);

CREATE TABLE EQUIPMENT
(
    EQUIPMENT_ID NUMBER,
    EQUIPMENT_TYPE VARCHAR2(100 BYTE),
    QUANTITY NUMBER DEFAULT 0,
    UNIT_PRICE NUMBER(12,2),
    STATUS VARCHAR2(20 BYTE) DEFAULT 'Available',
    DESCRIPTION CLOB,
    EMPLOYEE_ID NUMBER,
    PURCHASE_DATE DATE,
    LOCATION VARCHAR2(255 BYTE),
    NOTES CLOB,
    NEXT_MAINTENANCE DATE,
    COUT_ACQUISITION NUMBER(12,2),
    RESPONSABLE VARCHAR2(150 BYTE)
);

CREATE TABLE ORDERS
(
    ORDER_ID NUMBER,
    CLIENT_ID NUMBER,
    EMPLOYEE_ID NUMBER,
    ORDER_DATE TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    ORDER_TYPE VARCHAR2(100 BYTE),
    ORDER_STATUS VARCHAR2(20 BYTE) DEFAULT 'Pending',
    TOTAL_QUANTITY NUMBER DEFAULT 0,
    TOTAL_PRICE NUMBER(15,2) DEFAULT 0,
    PAYMENT_STATUS VARCHAR2(10 BYTE) DEFAULT 'Unpaid'
);

CREATE TABLE SUPPLIERS
(
    SUPPLIER_ID NUMBER,
    SUPPLIER_NAME VARCHAR2(150 BYTE),
    EMAIL VARCHAR2(150 BYTE),
    PHONE_NUMBER VARCHAR2(20 BYTE),
    ADDRESS VARCHAR2(255 BYTE),
    TYPE_NOTIFICATION VARCHAR2(100 BYTE),
    POSTAL_CODE VARCHAR2(20 BYTE),
    MESSAGE CLOB,
    EQUIPMENT_ID NUMBER,
    DELIVERY_RATING NUMBER(3,2),
    QUALITY_RATING NUMBER(3,2),
    RATING_ID NUMBER,
    RATING NUMBER(3,2),
    DELIVERY_NOTE CLOB,
    DELIVERY_DATE DATE,
    RATED_BY_EMPLOYEE_ID NUMBER,
    REGISTRATION_DATE DATE DEFAULT TRUNC(SYSDATE),
    ACCOUNT_STATUS VARCHAR2(20 BYTE) DEFAULT 'Active',
    OPENING_TIME VARCHAR2(5 BYTE),
    CLOSING_TIME VARCHAR2(5 BYTE),
    STOCK_STATUS VARCHAR2(20 BYTE) DEFAULT 'In Stock',
    RATINGS_JSON CLOB,
    AVERAGE_RATING NUMBER(3,2) DEFAULT 0,
    NOTIFICATIONS_JSON CLOB
);

------------------------------------------------------------------------
-- 3) CREATE SEQUENCES
------------------------------------------------------------------------

CREATE SEQUENCE CLIENTS_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EMPLOYEES_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EQUIPMENT_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE ORDERS_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE REQ_HIST_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SDR_SEQ MINVALUE 1 START WITH 21 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_CLIENTS MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EMPLOYE MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EMPLOYEES MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_EMPLOYES_ID MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_EQUIPMENT MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ORDERS MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SUPPLIERS MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SUPPLIER_NOTIF_SEQ MINVALUE 1 START WITH 21 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SUPPLIERS_SEQ MINVALUE 1 START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

------------------------------------------------------------------------
-- 4) CREATE TRIGGERS
------------------------------------------------------------------------

CREATE OR REPLACE TRIGGER TRG_CLIENTS_BI
BEFORE INSERT ON CLIENTS
FOR EACH ROW
BEGIN
    IF :NEW.CLIENT_ID IS NULL THEN
        SELECT SEQ_CLIENTS.NEXTVAL INTO :NEW.CLIENT_ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER TRG_CLIENTS_BI ENABLE;
/

CREATE OR REPLACE TRIGGER TRG_EMPLOYEES_BI
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
    IF :NEW.EMPLOYEE_ID IS NULL THEN
        SELECT SEQ_EMPLOYEES.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER TRG_EMPLOYEES_BI ENABLE;
/

CREATE OR REPLACE TRIGGER TRG_EQUIPMENT_BI
BEFORE INSERT ON EQUIPMENT
FOR EACH ROW
BEGIN
    IF :NEW.EQUIPMENT_ID IS NULL THEN
        SELECT SEQ_EQUIPMENT.NEXTVAL INTO :NEW.EQUIPMENT_ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER TRG_EQUIPMENT_BI ENABLE;
/

CREATE OR REPLACE TRIGGER TRG_ORDERS_BI
BEFORE INSERT ON ORDERS
FOR EACH ROW
BEGIN
    IF :NEW.ORDER_ID IS NULL THEN
        SELECT SEQ_ORDERS.NEXTVAL INTO :NEW.ORDER_ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER TRG_ORDERS_BI ENABLE;
/

CREATE OR REPLACE TRIGGER TRG_SUPPLIERS_BI
BEFORE INSERT ON SUPPLIERS
FOR EACH ROW
BEGIN
    IF :NEW.SUPPLIER_ID IS NULL THEN
        SELECT SEQ_SUPPLIERS.NEXTVAL INTO :NEW.SUPPLIER_ID FROM DUAL;
    END IF;
END;
/
ALTER TRIGGER TRG_SUPPLIERS_BI ENABLE;
/

------------------------------------------------------------------------
-- 5) CONSTRAINTS
------------------------------------------------------------------------

ALTER TABLE APP_HISTORY
    ADD CONSTRAINT PK_APP_HISTORY PRIMARY KEY (LOG_ID);

ALTER TABLE EMPLOYEES
    MODIFY (LAST_NAME NOT NULL, FIRST_NAME NOT NULL);

ALTER TABLE EMPLOYEES
    MODIFY (ADDRESS VARCHAR2(200) NOT NULL);

-- UK_EMPLOYEES_EMAIL constraint removed to allow multiple employees with same email

ALTER TABLE EMPLOYEES
    ADD CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPLOYEE_ID);

ALTER TABLE EMPLOYEES
    ADD CONSTRAINT CHK_EMPLOYEE_STATUS
    CHECK (EMPLOYEE_STATUS IN ('Active', 'Inactive', 'On Leave'));

ALTER TABLE CLIENTS
    MODIFY (LAST_NAME NOT NULL, FIRST_NAME NOT NULL);

ALTER TABLE CLIENTS
    ADD CONSTRAINT UK_CLIENTS_EMAIL UNIQUE (EMAIL);

ALTER TABLE CLIENTS
    ADD CONSTRAINT PK_CLIENTS PRIMARY KEY (CLIENT_ID);

ALTER TABLE CLIENTS
    ADD CONSTRAINT CHK_CLIENTS_GENDER
    CHECK (GENDER IN ('Male', 'Female', 'Other'));

ALTER TABLE CLIENTS
    ADD CONSTRAINT CHK_CLIENTS_STATUS
    CHECK (STATUS IN ('Active', 'Inactive', 'Suspended'));

ALTER TABLE EQUIPMENT
    MODIFY (EQUIPMENT_TYPE NOT NULL);

ALTER TABLE EQUIPMENT
    ADD CONSTRAINT PK_EQUIPMENT PRIMARY KEY (EQUIPMENT_ID);

ALTER TABLE EQUIPMENT
    ADD CONSTRAINT CHK_EQUIPMENT_STATUS
    CHECK (STATUS IN ('Available', 'In Use', 'Under Maintenance', 'Retired'));

ALTER TABLE ORDERS
    MODIFY (EMPLOYEE_ID NOT NULL, CLIENT_ID NOT NULL);

ALTER TABLE ORDERS
    ADD CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID);

ALTER TABLE ORDERS
    ADD CONSTRAINT CHK_PAYMENT_STATUS
    CHECK (PAYMENT_STATUS IN ('Unpaid', 'Partial', 'Paid'));

ALTER TABLE ORDERS
    ADD CONSTRAINT CHK_ORDER_STATUS
    CHECK (ORDER_STATUS IN ('Pending', 'Processing', 'Completed', 'Cancelled'));

ALTER TABLE SUPPLIERS
    MODIFY (SUPPLIER_NAME NOT NULL);

ALTER TABLE SUPPLIERS
    ADD CONSTRAINT UK_SUPPLIERS_EMAIL UNIQUE (EMAIL);

ALTER TABLE SUPPLIERS
    ADD CONSTRAINT PK_SUPPLIERS PRIMARY KEY (SUPPLIER_ID);

ALTER TABLE SUPPLIERS
    ADD CONSTRAINT CHK_ACCOUNT_STATUS
    CHECK (ACCOUNT_STATUS IN ('Active', 'Inactive', 'Suspended'));

------------------------------------------------------------------------
-- 6) FOREIGN KEYS
------------------------------------------------------------------------

ALTER TABLE CLIENTS
    ADD CONSTRAINT FK_CLIENTS_EMPLOYEE
    FOREIGN KEY (ASSIGNED_EMPLOYEE_ID)
    REFERENCES EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE EQUIPMENT
    ADD CONSTRAINT FK_EQUIPMENT_EMPLOYEE
    FOREIGN KEY (EMPLOYEE_ID)
    REFERENCES EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE ORDERS
    ADD CONSTRAINT FK_ORDERS_CLIENT
    FOREIGN KEY (CLIENT_ID)
    REFERENCES CLIENTS (CLIENT_ID);

ALTER TABLE ORDERS
    ADD CONSTRAINT FK_ORDERS_EMPLOYEE
    FOREIGN KEY (EMPLOYEE_ID)
    REFERENCES EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE SUPPLIERS
    ADD CONSTRAINT FK_SUPPLIERS_EMPLOYEE
    FOREIGN KEY (RATED_BY_EMPLOYEE_ID)
    REFERENCES EMPLOYEES (EMPLOYEE_ID);

ALTER TABLE SUPPLIERS
    ADD CONSTRAINT FK_SUPPLIERS_EQUIPMENT
    FOREIGN KEY (EQUIPMENT_ID)
    REFERENCES EQUIPMENT (EQUIPMENT_ID);

------------------------------------------------------------------------
-- 7) INSERT DATA
------------------------------------------------------------------------

INSERT INTO CLIENTS
(CLIENT_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,ADDRESS,GENDER,BIRTH_DATE,AGE,ACCOUNT_BALANCE,REGISTRATION_DATE,STATUS,ASSIGNED_EMPLOYEE_ID)
VALUES
(1,'Test','Client',NULL,NULL,NULL,NULL,NULL,NULL,0,TO_DATE('23/02/26','DD/MM/RR'),'Active',NULL);

INSERT INTO EMPLOYEES
(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,JOB_TITLE,EMAIL,PHONE_NUMBER,SALARY,PASSWORD,DEPARTMENT,BIRTH_DATE,AGE,HIRE_DATE,EMPLOYEE_STATUS,ADDRESS)
VALUES
(1,'semi','fehri','battal','fehri@s.com','9898898',15,'4','btala',TO_DATE('20/02/26','DD/MM/RR'),45,TO_DATE('27/02/26','DD/MM/RR'),'Active','Not specified');

INSERT INTO EMPLOYEES
(EMPLOYEE_ID,FIRST_NAME,LAST_NAME,JOB_TITLE,EMAIL,PHONE_NUMBER,SALARY,PASSWORD,DEPARTMENT,BIRTH_DATE,AGE,HIRE_DATE,EMPLOYEE_STATUS,ADDRESS)
VALUES
(2,'Guest','User','Administrator','guest@system.com','0000000',5000,'1','Administration',TO_DATE('01/01/90','DD/MM/RR'),35,TO_DATE('01/01/24','DD/MM/RR'),'Active','System Default');

INSERT INTO SUPPLIERS
(SUPPLIER_ID,SUPPLIER_NAME,EMAIL,PHONE_NUMBER,ADDRESS,TYPE_NOTIFICATION,POSTAL_CODE,EQUIPMENT_ID,DELIVERY_RATING,QUALITY_RATING,RATING_ID,RATING,DELIVERY_DATE,RATED_BY_EMPLOYEE_ID,REGISTRATION_DATE,ACCOUNT_STATUS,OPENING_TIME,CLOSING_TIME,STOCK_STATUS,AVERAGE_RATING)
VALUES
(9999,'Tunisz Woodworks','soussewood@example.com','555-0000','Avenue Habib Bourguiba, Sousse','Lumber','4000',NULL,NULL,NULL,NULL,NULL,NULL,TO_DATE('23/03/26','DD/MM/RR'),'Active',NULL,NULL,'In Stock',0);

INSERT INTO SUPPLIERS
(SUPPLIER_ID,SUPPLIER_NAME,EMAIL,PHONE_NUMBER,ADDRESS,TYPE_NOTIFICATION,POSTAL_CODE,EQUIPMENT_ID,DELIVERY_RATING,QUALITY_RATING,RATING_ID,RATING,DELIVERY_DATE,RATED_BY_EMPLOYEE_ID,REGISTRATION_DATE,ACCOUNT_STATUS,OPENING_TIME,CLOSING_TIME,STOCK_STATUS,AVERAGE_RATING)
VALUES
(2,'eogneron','fgtyjtjyttjj@gokejrg.com',NULL,'onoinononrge','rgrthy','42',NULL,NULL,NULL,NULL,NULL,NULL,NULL,TO_DATE('24/03/26','DD/MM/RR'),'Active','08:00','18:00','In Stock',0);

INSERT INTO SUPPLIERS
(SUPPLIER_ID,SUPPLIER_NAME,EMAIL,PHONE_NUMBER,ADDRESS,TYPE_NOTIFICATION,POSTAL_CODE,EQUIPMENT_ID,DELIVERY_RATING,QUALITY_RATING,RATING_ID,RATING,DELIVERY_DATE,RATED_BY_EMPLOYEE_ID,REGISTRATION_DATE,ACCOUNT_STATUS,OPENING_TIME,CLOSING_TIME,STOCK_STATUS,AVERAGE_RATING)
VALUES
(3,'1553','guiuiguig','987979','ojzjeozpj','iuguig','3',NULL,NULL,NULL,NULL,NULL,NULL,NULL,TO_DATE('25/03/26','DD/MM/RR'),'Active','08:00','18:00','In Stock',0);

INSERT INTO SUPPLIERS
(SUPPLIER_ID,SUPPLIER_NAME,EMAIL,PHONE_NUMBER,ADDRESS,TYPE_NOTIFICATION,POSTAL_CODE,EQUIPMENT_ID,DELIVERY_RATING,QUALITY_RATING,RATING_ID,RATING,DELIVERY_DATE,RATED_BY_EMPLOYEE_ID,REGISTRATION_DATE,ACCOUNT_STATUS,OPENING_TIME,CLOSING_TIME,STOCK_STATUS,AVERAGE_RATING)
VALUES
(9,'oijgoiejog','egjerjo','89789','oijiojoi','opjopj','0',NULL,NULL,NULL,NULL,NULL,NULL,NULL,TO_DATE('25/03/26','DD/MM/RR'),'Active','08:00','18:00','In Stock',0);

INSERT INTO SUPPLIERS
(SUPPLIER_ID,SUPPLIER_NAME,EMAIL,PHONE_NUMBER,ADDRESS,TYPE_NOTIFICATION,POSTAL_CODE,EQUIPMENT_ID,DELIVERY_RATING,QUALITY_RATING,RATING_ID,RATING,DELIVERY_DATE,RATED_BY_EMPLOYEE_ID,REGISTRATION_DATE,ACCOUNT_STATUS,OPENING_TIME,CLOSING_TIME,STOCK_STATUS,AVERAGE_RATING)
VALUES
(55,'joijoij','iojoijioj@iofjoi.com','98789798','iojoijoi','kergerg','55',NULL,NULL,NULL,NULL,NULL,NULL,NULL,TO_DATE('26/03/26','DD/MM/RR'),'Active','08:00','18:00','In Stock',0);

INSERT INTO SUPPLIERS
(SUPPLIER_ID,SUPPLIER_NAME,EMAIL,PHONE_NUMBER,ADDRESS,TYPE_NOTIFICATION,POSTAL_CODE,EQUIPMENT_ID,DELIVERY_RATING,QUALITY_RATING,RATING_ID,RATING,DELIVERY_DATE,RATED_BY_EMPLOYEE_ID,REGISTRATION_DATE,ACCOUNT_STATUS,OPENING_TIME,CLOSING_TIME,STOCK_STATUS,AVERAGE_RATING)
VALUES
(899,'koprgop','oitrjhijtroithj@oijio.com','89878987','ortjiorj','iojoijoi','55',NULL,NULL,NULL,NULL,NULL,NULL,NULL,TO_DATE('26/03/26','DD/MM/RR'),'Active','08:00','18:00','In Stock',0);

COMMIT;
