
--------------------------------------------------------
-- Drop existing objects safely
--------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ORDERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SUPPLIERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EQUIPMENT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CLIENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Drop sequences
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE CLIENTS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE EMPLOYEES_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE EQUIPMENT_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ORDERS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SDR_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLIENTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EMPLOYE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EMPLOYEES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EMPLOYES_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EQUIPMENT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ORDERS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SUPPLIERS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SUPPLIERS_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Drop triggers
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_CLIENTS_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_EMPLOYEES_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_EQUIPMENT_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ORDERS_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_SUPPLIERS_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

--------------------------------------------------------
-- DDL for Sequences
--------------------------------------------------------
CREATE SEQUENCE CLIENTS_SEQ   MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
/
CREATE SEQUENCE EMPLOYEES_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
/
CREATE SEQUENCE EQUIPMENT_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
/
CREATE SEQUENCE ORDERS_SEQ    MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
/
CREATE SEQUENCE SDR_SEQ       MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
/
CREATE SEQUENCE SEQ_CLIENTS   MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
/
CREATE SEQUENCE SEQ_EMPLOYE   MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
/
CREATE SEQUENCE SEQ_EMPLOYEES MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
/
CREATE SEQUENCE SEQ_EMPLOYES_ID MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;
/
CREATE SEQUENCE SEQ_EQUIPMENT MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
/
CREATE SEQUENCE SEQ_ORDERS    MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
/
CREATE SEQUENCE SEQ_SUPPLIERS MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
/
CREATE SEQUENCE SUPPLIERS_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;
/

--------------------------------------------------------
-- DDL for Table EMPLOYEES (created first - referenced by others)
--------------------------------------------------------
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID     NUMBER          NOT NULL,
    FIRST_NAME      VARCHAR2(100)   NOT NULL,
    LAST_NAME       VARCHAR2(100)   NOT NULL,
    JOB_TITLE       VARCHAR2(100),
    EMAIL           VARCHAR2(150),
    PHONE_NUMBER    VARCHAR2(20),
    SALARY          NUMBER(12,2),
    PASSWORD        VARCHAR2(255),
    DEPARTMENT      VARCHAR2(100),
    BIRTH_DATE      DATE,
    AGE             NUMBER,
    HIRE_DATE       DATE            DEFAULT TRUNC(SYSDATE),
    EMPLOYEE_STATUS VARCHAR2(20)    DEFAULT 'Active',
    CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT UQ_EMPLOYEES_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CHK_EMPLOYEES_STATUS CHECK (EMPLOYEE_STATUS IN ('Active', 'Inactive', 'On Leave'))
);
/

--------------------------------------------------------
-- DDL for Table CLIENTS
--------------------------------------------------------
CREATE TABLE CLIENTS (
    CLIENT_ID           NUMBER          NOT NULL,
    FIRST_NAME          VARCHAR2(100)   NOT NULL,
    LAST_NAME           VARCHAR2(100)   NOT NULL,
    EMAIL               VARCHAR2(150),
    PHONE_NUMBER        VARCHAR2(20),
    ADDRESS             VARCHAR2(255),
    GENDER              VARCHAR2(10),
    BIRTH_DATE          DATE,
    AGE                 NUMBER,
    ACCOUNT_BALANCE     NUMBER(15,2)    DEFAULT 0,
    REGISTRATION_DATE   DATE            DEFAULT TRUNC(SYSDATE),
    STATUS              VARCHAR2(20)    DEFAULT 'Active',
    ASSIGNED_EMPLOYEE_ID NUMBER,
    CONSTRAINT PK_CLIENTS PRIMARY KEY (CLIENT_ID),
    CONSTRAINT UQ_CLIENTS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CHK_CLIENTS_STATUS CHECK (STATUS IN ('Active', 'Inactive', 'Suspended')),
    CONSTRAINT CHK_CLIENTS_GENDER CHECK (GENDER IN ('Male', 'Female', 'Other')),
    CONSTRAINT FK_CLIENTS_EMPLOYEE FOREIGN KEY (ASSIGNED_EMPLOYEE_ID)
        REFERENCES EMPLOYEES (EMPLOYEE_ID)
);
/

--------------------------------------------------------
-- DDL for Table EQUIPMENT
--------------------------------------------------------
CREATE TABLE EQUIPMENT (
    EQUIPMENT_ID      NUMBER          NOT NULL,
    EQUIPMENT_TYPE    VARCHAR2(100)   NOT NULL,
    QUANTITY          NUMBER          DEFAULT 0,
    UNIT_PRICE        NUMBER(12,2),
    STATUS            VARCHAR2(20)    DEFAULT 'Available',
    DESCRIPTION       CLOB,
    EMPLOYEE_ID       NUMBER,
    PURCHASE_DATE     DATE,
    LOCATION          VARCHAR2(255),
    NOTES             CLOB,
    NEXT_MAINTENANCE  DATE,
    COUT_ACQUISITION  NUMBER(12,2),
    RESPONSABLE       VARCHAR2(150),
    CONSTRAINT PK_EQUIPMENT PRIMARY KEY (EQUIPMENT_ID),
    CONSTRAINT CHK_EQUIPMENT_STATUS CHECK (STATUS IN ('Available', 'In Use', 'Under Maintenance', 'Retired')),
    CONSTRAINT FK_EQUIPMENT_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEES (EMPLOYEE_ID)
);
/

--------------------------------------------------------
-- DDL for Table ORDERS
--------------------------------------------------------
CREATE TABLE ORDERS (
    ORDER_ID        NUMBER          NOT NULL,
    CLIENT_ID       NUMBER          NOT NULL,
    EMPLOYEE_ID     NUMBER          NOT NULL,
    ORDER_DATE      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    ORDER_TYPE      VARCHAR2(100),
    ORDER_STATUS    VARCHAR2(20)    DEFAULT 'Pending',
    TOTAL_QUANTITY  NUMBER          DEFAULT 0,
    TOTAL_PRICE     NUMBER(15,2)    DEFAULT 0,
    PAYMENT_STATUS  VARCHAR2(10)    DEFAULT 'Unpaid',
    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID),
    CONSTRAINT CHK_ORDERS_PAYMENT CHECK (PAYMENT_STATUS IN ('Unpaid', 'Partial', 'Paid')),
    CONSTRAINT CHK_ORDERS_STATUS  CHECK (ORDER_STATUS IN ('Pending', 'Processing', 'Completed', 'Cancelled')),
    CONSTRAINT FK_ORDERS_CLIENT   FOREIGN KEY (CLIENT_ID)   REFERENCES CLIENTS   (CLIENT_ID),
    CONSTRAINT FK_ORDERS_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID)
);
/

--------------------------------------------------------
-- DDL for Table SUPPLIERS
--------------------------------------------------------
CREATE TABLE SUPPLIERS (
    SUPPLIER_ID          NUMBER          NOT NULL,
    SUPPLIER_NAME        VARCHAR2(150)   NOT NULL,
    EMAIL                VARCHAR2(150),
    PHONE_NUMBER         VARCHAR2(20),
    ADDRESS              VARCHAR2(255),
    TYPE_NOTIFICATION    VARCHAR2(100),
    POSTAL_CODE          VARCHAR2(20),
    MESSAGE              CLOB,
    EQUIPMENT_ID         NUMBER,
    DELIVERY_RATING      NUMBER(3,2),
    QUALITY_RATING       NUMBER(3,2),
    RATING_ID            NUMBER,
    RATING               NUMBER(3,2),
    DELIVERY_NOTE        CLOB,
    DELIVERY_DATE        DATE,
    RATED_BY_EMPLOYEE_ID NUMBER,
    REGISTRATION_DATE    DATE            DEFAULT TRUNC(SYSDATE),
    ACCOUNT_STATUS       VARCHAR2(20)    DEFAULT 'Active',
    CONSTRAINT PK_SUPPLIERS PRIMARY KEY (SUPPLIER_ID),
    CONSTRAINT UQ_SUPPLIERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CHK_SUPPLIERS_STATUS CHECK (ACCOUNT_STATUS IN ('Active', 'Inactive', 'Suspended')),
    CONSTRAINT FK_SUPPLIERS_EMPLOYEE  FOREIGN KEY (RATED_BY_EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID),
    CONSTRAINT FK_SUPPLIERS_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID)         REFERENCES EQUIPMENT  (EQUIPMENT_ID)
);
/

--------------------------------------------------------
-- DDL for Triggers (auto-generate IDs if not provided)
--------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_EMPLOYEES_BI
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
    IF :NEW.EMPLOYEE_ID IS NULL THEN
        SELECT SEQ_EMPLOYEES.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_CLIENTS_BI
BEFORE INSERT ON CLIENTS
FOR EACH ROW
BEGIN
    IF :NEW.CLIENT_ID IS NULL THEN
        SELECT SEQ_CLIENTS.NEXTVAL INTO :NEW.CLIENT_ID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_EQUIPMENT_BI
BEFORE INSERT ON EQUIPMENT
FOR EACH ROW
BEGIN
    IF :NEW.EQUIPMENT_ID IS NULL THEN
        SELECT SEQ_EQUIPMENT.NEXTVAL INTO :NEW.EQUIPMENT_ID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ORDERS_BI
BEFORE INSERT ON ORDERS
FOR EACH ROW
BEGIN
    IF :NEW.ORDER_ID IS NULL THEN
        SELECT SEQ_ORDERS.NEXTVAL INTO :NEW.ORDER_ID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_SUPPLIERS_BI
BEFORE INSERT ON SUPPLIERS
FOR EACH ROW
BEGIN
    IF :NEW.SUPPLIER_ID IS NULL THEN
        SELECT SEQ_SUPPLIERS.NEXTVAL INTO :NEW.SUPPLIER_ID FROM DUAL;
    END IF;
END;
/

--------------------------------------------------------
-- Populate Data
--------------------------------------------------------
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_TITLE, EMAIL, PHONE_NUMBER, SALARY, PASSWORD, AGE)
VALUES (1, 'Admin', 'User', 'Administrator', 'admin@esprit.tn', '12345678', 5000, '4', 30);

COMMIT;
