INSERT INTO SUPPLIERS (SUPPLIER_ID, SUPPLIER_NAME, ADDRESS, EMAIL, PHONE_NUMBER, TYPE_NOTIFICATION, POSTAL_CODE, REGISTRATION_DATE, ACCOUNT_STATUS, OPENING_TIME, CLOSING_TIME) 
VALUES (9991, 'Tech Supplies Tunis', 'Avenue Habib Bourguiba', 'tech@tunis.tn', '12345678', 'Email', 1000, SYSDATE, 'Active', '00:00', '23:59');

INSERT INTO SUPPLIERS (SUPPLIER_ID, SUPPLIER_NAME, ADDRESS, EMAIL, PHONE_NUMBER, TYPE_NOTIFICATION, POSTAL_CODE, REGISTRATION_DATE, ACCOUNT_STATUS, OPENING_TIME, CLOSING_TIME) 
VALUES (9992, 'Marsa Hardware', 'La Marsa', 'hardware@marsa.tn', '87654321', 'SMS', 2070, SYSDATE, 'Active', '08:00', '16:00');

INSERT INTO SUPPLIERS (SUPPLIER_ID, SUPPLIER_NAME, ADDRESS, EMAIL, PHONE_NUMBER, TYPE_NOTIFICATION, POSTAL_CODE, REGISTRATION_DATE, ACCOUNT_STATUS, OPENING_TIME, CLOSING_TIME) 
VALUES (9993, 'Carthage Materials', 'Carthage', 'materials@carthage.tn', '55555555', 'Both', 2016, SYSDATE, 'Active', '09:00', '18:00');

COMMIT;
EXIT;
