-- ==============================================================================
-- HammerDown Database Schema (Oracle SQL)
-- Script to initialize database tables, constraints, sequences, triggers, and mock data.
-- ==============================================================================

-- 1. DROP EXISTING OBJECTS (To facilitate clean re-runs)
-- ==============================================================================
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EQUIPMENT_HISTORY CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ORDERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EQUIPMENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE SUPPLIERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CLIENTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE EQUIPMENT_HISTORY_SEQ';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -2289 THEN RAISE; END IF; END;
/

-- 2. CREATE TABLES
-- ==============================================================================

-- A. EMPLOYEES Table
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(100 CHAR) NOT NULL,
    LAST_NAME VARCHAR2(100 CHAR) NOT NULL,
    JOB_TITLE VARCHAR2(100 CHAR) NOT NULL,
    EMAIL VARCHAR2(255 CHAR) UNIQUE,
    PHONE_NUMBER VARCHAR2(20 CHAR),
    ADDRESS VARCHAR2(500 CHAR),
    SALARY NUMBER(10, 2) NOT NULL,
    DEPARTMENT VARCHAR2(100 CHAR),
    AGE NUMBER,
    EMPLOYEE_STATUS VARCHAR2(50 CHAR) DEFAULT 'Active',
    PASSWORD VARCHAR2(255 CHAR),
    HIRE_DATE DATE DEFAULT SYSDATE NOT NULL
);
/

-- B. CLIENTS Table
CREATE TABLE CLIENTS (
    CLIENT_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(100 CHAR) NOT NULL,
    LAST_NAME VARCHAR2(100 CHAR) NOT NULL,
    EMAIL VARCHAR2(255 CHAR) UNIQUE,
    PHONE_NUMBER VARCHAR2(20 CHAR),
    ADDRESS VARCHAR2(500 CHAR),
    GENDER VARCHAR2(20 CHAR),
    AGE NUMBER,
    ACCOUNT_BALANCE NUMBER(12, 2) DEFAULT 0.00 NOT NULL,
    STATUS VARCHAR2(50 CHAR) DEFAULT 'Active'
);
/

-- C. SUPPLIERS Table
CREATE TABLE SUPPLIERS (
    SUPPLIER_ID NUMBER PRIMARY KEY,
    SUPPLIER_NAME VARCHAR2(255 CHAR) NOT NULL,
    EMAIL VARCHAR2(255 CHAR) UNIQUE,
    PHONE_NUMBER VARCHAR2(20 CHAR),
    ADDRESS VARCHAR2(500 CHAR),
    POSTAL_CODE VARCHAR2(20 CHAR),
    DELIVERY_RATING NUMBER(3, 2) DEFAULT 5.00,
    QUALITY_RATING NUMBER(3, 2) DEFAULT 5.00,
    ACCOUNT_STATUS VARCHAR2(50 CHAR) DEFAULT 'Active'
);
/

-- D. EQUIPMENT Table
CREATE TABLE EQUIPMENT (
    EQUIPMENT_ID NUMBER PRIMARY KEY,
    EQUIPMENT_TYPE VARCHAR2(255 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(4000 CHAR),
    STATUS VARCHAR2(100 CHAR) DEFAULT 'Available' NOT NULL,
    PURCHASE_DATE DATE DEFAULT SYSDATE NOT NULL,
    EMPLOYEE_ID NUMBER,
    UNIT_PRICE NUMBER(12, 2),
    QUANTITY NUMBER DEFAULT 1 NOT NULL,
    LOCATION VARCHAR2(255 CHAR),
    RESPONSABLE VARCHAR2(255 CHAR),
    COUT_ACQUISITION NUMBER(12, 2),
    CONSTRAINT FK_EQUIPMENT_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE SET NULL
);
/

-- E. ORDERS Table
CREATE TABLE ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    CLIENT_ID NUMBER NOT NULL,
    EMPLOYEE_ID NUMBER,
    ORDER_TYPE VARCHAR2(255 CHAR) NOT NULL,
    TOTAL_QUANTITY NUMBER DEFAULT 1 NOT NULL,
    TOTAL_PRICE NUMBER(12, 2) NOT NULL,
    ORDER_DATE DATE DEFAULT SYSDATE NOT NULL,
    ORDER_STATUS VARCHAR2(100 CHAR) DEFAULT 'Pending' NOT NULL,
    PAYMENT_STATUS VARCHAR2(100 CHAR) DEFAULT 'Unpaid' NOT NULL,
    CONSTRAINT FK_ORDERS_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_ORDERS_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE SET NULL
);
/

-- F. EQUIPMENT_HISTORY Audit Table
CREATE TABLE EQUIPMENT_HISTORY (
    HISTORY_ID NUMBER PRIMARY KEY,
    EQUIPMENT_ID NUMBER,
    OPERATION_TYPE VARCHAR2(10 CHAR) NOT NULL,
    EQUIPMENT_TYPE VARCHAR2(255 CHAR),
    DESCRIPTION VARCHAR2(4000 CHAR),
    STATUS VARCHAR2(100 CHAR),
    UNIT_PRICE NUMBER(12,2),
    QUANTITY NUMBER,
    CHANGE_DATE DATE DEFAULT SYSDATE NOT NULL,
    CHANGED_BY VARCHAR2(128 CHAR)
);
/

-- 3. CREATE SEQUENCES, INDEXES, AND TRIGGERS
-- ==============================================================================

-- Create sequence for Audit logs
CREATE SEQUENCE EQUIPMENT_HISTORY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
/

-- Create index for faster history lookups
CREATE INDEX IDX_EQUIPMENT_HISTORY_OP_DATE ON EQUIPMENT_HISTORY (OPERATION_TYPE, CHANGE_DATE);
/

-- Audit Trigger to capture inserts, updates, and deletes on EQUIPMENT
CREATE OR REPLACE TRIGGER TRG_EQUIPMENT_HISTORY_AUDIT
AFTER INSERT OR UPDATE OR DELETE ON EQUIPMENT
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO EQUIPMENT_HISTORY (
            HISTORY_ID, EQUIPMENT_ID, OPERATION_TYPE, EQUIPMENT_TYPE, DESCRIPTION,
            STATUS, UNIT_PRICE, QUANTITY, CHANGE_DATE, CHANGED_BY
        ) VALUES (
            EQUIPMENT_HISTORY_SEQ.NEXTVAL,
            :NEW.EQUIPMENT_ID,
            'ADD',
            :NEW.EQUIPMENT_TYPE,
            :NEW.DESCRIPTION,
            :NEW.STATUS,
            :NEW.UNIT_PRICE,
            :NEW.QUANTITY,
            SYSDATE,
            USER
        );
    ELSIF UPDATING THEN
        INSERT INTO EQUIPMENT_HISTORY (
            HISTORY_ID, EQUIPMENT_ID, OPERATION_TYPE, EQUIPMENT_TYPE, DESCRIPTION,
            STATUS, UNIT_PRICE, QUANTITY, CHANGE_DATE, CHANGED_BY
        ) VALUES (
            EQUIPMENT_HISTORY_SEQ.NEXTVAL,
            :NEW.EQUIPMENT_ID,
            'MODIFY',
            :NEW.EQUIPMENT_TYPE,
            :NEW.DESCRIPTION,
            :NEW.STATUS,
            :NEW.UNIT_PRICE,
            :NEW.QUANTITY,
            SYSDATE,
            USER
        );
    ELSIF DELETING THEN
        INSERT INTO EQUIPMENT_HISTORY (
            HISTORY_ID, EQUIPMENT_ID, OPERATION_TYPE, EQUIPMENT_TYPE, DESCRIPTION,
            STATUS, UNIT_PRICE, QUANTITY, CHANGE_DATE, CHANGED_BY
        ) VALUES (
            EQUIPMENT_HISTORY_SEQ.NEXTVAL,
            :OLD.EQUIPMENT_ID,
            'DELETE',
            :OLD.EQUIPMENT_TYPE,
            :OLD.DESCRIPTION,
            :OLD.STATUS,
            :OLD.UNIT_PRICE,
            :OLD.QUANTITY,
            SYSDATE,
            USER
        );
    END IF;
END;
/


-- 4. INSERT TEST DEMO DATA
-- ==============================================================================

-- A. Insert Test Employees (Admin credentials & staff)
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_TITLE, EMAIL, PHONE_NUMBER, ADDRESS, SALARY, DEPARTMENT, AGE, EMPLOYEE_STATUS, PASSWORD, HIRE_DATE)
VALUES (1, 'Rami', 'Ben Slimen', 'Workshop Manager', 'rami.benslimen@hammerdown.tn', '20123456', 'Tunis, Tunisia', 3500.00, 'Administration', 32, 'Active', 'rami123', SYSDATE - 365);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_TITLE, EMAIL, PHONE_NUMBER, ADDRESS, SALARY, DEPARTMENT, AGE, EMPLOYEE_STATUS, PASSWORD, HIRE_DATE)
VALUES (2, 'Mohamed', 'Trabelsi', 'Master Carpenter', 'mohamed.trabelsi@hammerdown.tn', '22345678', 'Ariana, Tunis', 2800.00, 'Production', 30, 'Active', 'mohamed123', SYSDATE - 200);

-- B. Insert Test Clients
INSERT INTO CLIENTS (CLIENT_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, GENDER, AGE, ACCOUNT_BALANCE, STATUS)
VALUES (1, 'Test', 'Client', 'test.client@gmail.com', '98765432', 'Lac 2, Tunis', 'Male', 35, 1200.00, 'Active');

INSERT INTO CLIENTS (CLIENT_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, GENDER, AGE, ACCOUNT_BALANCE, STATUS)
VALUES (2, 'Ines', 'Mejri', 'ines.mejri@client.tn', '55123456', 'Sfax, Tunisia', 'Female', 28, 0.00, 'Active');

-- C. Insert Test Suppliers
INSERT INTO SUPPLIERS (SUPPLIER_ID, SUPPLIER_NAME, EMAIL, PHONE_NUMBER, ADDRESS, POSTAL_CODE, DELIVERY_RATING, QUALITY_RATING, ACCOUNT_STATUS)
VALUES (1, 'Bois Tunisie SARL', 'contact@boistunisie.tn', '71234567', 'Tunis Industrial Zone', '1000', 4.80, 4.90, 'Active');

INSERT INTO SUPPLIERS (SUPPLIER_ID, SUPPLIER_NAME, EMAIL, PHONE_NUMBER, ADDRESS, POSTAL_CODE, DELIVERY_RATING, QUALITY_RATING, ACCOUNT_STATUS)
VALUES (2, 'MetalWorks Tunisia', 'info@metalworks.tn', '72345678', 'Sousse Industrial Zone', '4000', 4.20, 4.50, 'Active');

-- D. Insert Test Equipments (Trigger will log these in EQUIPMENT_HISTORY automatically)
INSERT INTO EQUIPMENT (EQUIPMENT_ID, EQUIPMENT_TYPE, DESCRIPTION, STATUS, PURCHASE_DATE, EMPLOYEE_ID, UNIT_PRICE, QUANTITY, LOCATION, RESPONSABLE, COUT_ACQUISITION)
VALUES (1, 'Table Saw', 'Industrial wood table saw', 'Available', SYSDATE - 50, 2, 1500.00, 2, 'Workshop A', 'Mohamed Trabelsi', 3000.00);

INSERT INTO EQUIPMENT (EQUIPMENT_ID, EQUIPMENT_TYPE, DESCRIPTION, STATUS, PURCHASE_DATE, EMPLOYEE_ID, UNIT_PRICE, QUANTITY, LOCATION, RESPONSABLE, COUT_ACQUISITION)
VALUES (2, 'Drill Press', 'Heavy duty vertical drill press', 'In Use', SYSDATE - 30, 2, 850.00, 1, 'Workshop B', 'Mohamed Trabelsi', 850.00);

-- E. Insert Test Orders
INSERT INTO ORDERS (ORDER_ID, CLIENT_ID, EMPLOYEE_ID, ORDER_TYPE, TOTAL_QUANTITY, TOTAL_PRICE, ORDER_DATE, ORDER_STATUS, PAYMENT_STATUS)
VALUES (1, 1, 2, 'Dining Table', 1, 950.00, SYSDATE - 5, 'Pending', 'Unpaid');

INSERT INTO ORDERS (ORDER_ID, CLIENT_ID, EMPLOYEE_ID, ORDER_TYPE, TOTAL_QUANTITY, TOTAL_PRICE, ORDER_DATE, ORDER_STATUS, PAYMENT_STATUS)
VALUES (2, 2, 2, 'Oak Chairs', 6, 1200.00, SYSDATE - 2, 'Completed', 'Paid');

-- Commit changes
COMMIT;
/
